services:
  app:
    container_name: app_test
    build:
      context: ./app
      dockerfile: Dockerfile
  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.2}
    container_name: loki_test
    ports:
      - "12004:3100"
    volumes:
     - ./grafana/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
   image: grafana/grafana:${GRAFANA_VERSION:-12.1.0}
   container_name: grafana_test
   environment:
     GF_AUTH_ANONYMOUS_ENABLED: true
     GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
     GF_AUTH_DISABLE_LOGIN_FORM: "true"
     GF_SERVER_ROOT_URL: "http://localhost:12000"
   ports:
     - 12000:3000/tcp
   volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
  alloy:
   image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.10.0}
   container_name: alloy_test
   user: root
   privileged: true
   pid: host
   ports:
     - 12001:12345 # Alloy UI
     - 12002:4317
     - 12003:4318
   volumes:
     - ./grafana/config.alloy:/etc/alloy/config.alloy:ro
     - /var/run/docker.sock:/var/run/docker.sock
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

