[project]
name = "app"
version = "0.1.0"
description = "An app that continuously generates log messages."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.5",
]
